{{- if and .Values.oauth.clientId .Values.oauth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client_id: {{ .Values.oauth.clientId | quote }}
  client_secret: {{ .Values.oauth.clientSecret | quote }}
{{- end }}
